#' Convert character strings to Parsons code
#'
#'@author Ari Cross, Grace Smith-Vidaurre
#'
#'@description This function generates Parsons code from the character strings produced by `generate_strings()`.
#'
#' @param df Data frame. A data frame object produced by `generate_strings()`. Each row is a string of characters representing a vocalization.
#' @param string_col Character string. The name of the column in `df` that contains the strings.
#' @param mapping List. A list for Parsons code mapping. Each list element contains the each character value and its corresponding directionality in Parsons code. The default mapping are the first three letters of the alphabet in uppercase, to create a  mapping for 1-base Parsons code (three unique directions: up, down, and constant).
#'
#' @details This function converts the character strings generated by `generate_strings()` to Parsons code. The current version of this function was written for 1-base Parsons code and has not been tested for finer-grained Parsons code. The assignment of character values to each Parsons code value is subjective, and changing this mapping will change how frequency modulation patterns are generated downstream.
#'
#' @return The same data frame that was used as input for the function, with an additional column of the string converted to Parsons code.
#'
#' @examples
#' seed <- 8
#' set.seed(seed) # For reproducibility
#' library(tidyverse)
#'
#' example_calls <- generate_strings(n_groups = 2, n_individuals = 5, n_calls = 10, string_length = 16, group_information = 8, individual_information = 2)
#'
#' example_calls_parsons <- parsons_code(example_calls, "Call", list("A" = "up", "B" = "down", "C" = "constant"))
#' glimpse(example_calls_parsons)
#'
#' @export parsons_code

parsons_code <- function(df, string_col, mapping = list("A" = "up", "B" = "down", "C" = "constant")) {

  df %>%
    dplyr::mutate(Parsons_Code = sapply(!!rlang::sym(string_col), function(string) paste(convert_to_parsons_code(string, mapping), collapse = "-")))

}

# Helper function to generate Parsons code for existing sequences
convert_to_parsons_code <- function(string, mapping) {
  sapply(strsplit(string, NULL)[[1]], function(char) mapping[[char]], USE.NAMES = FALSE)
}
