#' Generate Parsons Code from character strings
#'
#'@author Ari Cross, Grace Smith-Vidaurre
#'
#' This function generates Parsons code from the character strings generated by the call_gen function.
#'
#' @param df data frame containing strings of "A", "B", "C".
#' @param string_col name of column containing strings.
#' @param mapping Parsons code mapping corresponding to strings. The default mapping are the first three letters of the alphabet in upper case and in list format, to createa  mapping for 1-base Parsons code (three unique characters).
#' @return A data frame containing Parsons Code based on the call column.
#' @examples
#' set.seed(3)  # For reproducibility
#' gd_calls_parsons <- add_parsons_code(gd_calls, "Call", parsons_code_mapping)
#' @export parsons_code
parsons_code <- function(df, string_col, mapping = list("A" = "up", "B" = "down", "C" = "constant")) {
  df %>%
    dplyr::mutate(Parsons_Code = sapply(!!rlang::sym(string_col), function(string) paste(convert_to_parsons_code(string, mapping), collapse = "-")))
}

# Helper function to generate Parsons code for existing sequences
convert_to_parsons_code <- function(string, mapping) {
  sapply(strsplit(string, NULL)[[1]], function(char) mapping[[char]], USE.NAMES = FALSE)
}
